services:
  altcha.sentinel.validator:
    class: Tito10047\AltchaBundle\Validator\AltchaSentinelValidator
    tags: ['validator.constraint_validator']
    arguments:
      $enable: '%altcha.enable%'
      $apiKey: '%altcha.sentinel.api_key%'
      $verifySignatureUrl: '%altcha.sentinel.verify_signature_url%'
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $requestStack: '@request_stack'
      $hmacKey: '%altcha.hmacKey%'
    calls:
      - setLogger: ['@?logger']
